### ISSUE TITLE
multi support

### ISSUE THREAD

**Issue by kostya** [blocknotes/curl-crystal#1]
hi, thanks for nice binding,
is there any plans to support multi interface, and map it crystal channels?

**Comment by kostya** [comment]
actually this is not needed, because this lib works fine with crystal threads.

**Comment by blocknotes** [comment]
Thank you for your comment @kostya

**Comment by kostya** [comment]
because lib curl is blocking, for concurrency i use thread pool: https://github.com/kostya/thread_pool, with size 150, works pretty stable.

**Comment by kostya** [comment]
i added lib https://github.com/kostya/curl-downloader, based on your binding, thanks.
